#!/usr/bin/env bash

set -eu -o pipefail -x

# update this to iidfile after 17.06
docker build --build-arg VNDR_VERSION=48ac2669d9d1bcacd3163650ef911edca2ec3b42 -t opentracing-registry:vendor -f ./hack/dockerfiles/vendor.Dockerfile --force-rm .
cid=$(docker create opentracing-registry:vendor noop)
rm -rf ./vendor
docker cp $cid:/go/src/github.com/hinshun/opentracing-registry/vendor .
docker rm $cid
